version: "3"
services:
   node-app:
    container_name: my-new-app-cont
    build: .
    depends_on:
     - postgres
     - redis
    ports:
      - "4004:4004"
    env_file:
      - ./.env
   redis:
    image: redis
  
   nginx:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "80:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
   postgres:
    image: postgres
    restart: always
    volumes:
     - postgres-dp:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
volumes:
  postgres-dp:
 
    
